name: MEAN Stack CI

on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:   
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd backend && npm install
    - run: cd backend && npm run build --if-present
    - run: touch ./backend/.env.test && 
          echo MONGO_DB_URL=mongodb://127.0.0.1:27001/jest >> ./backend/.env.test && 
          echo SECRET_TOKEN=testingToken >> ./backend/.env.test &&
          echo "CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}" >> ./backend/.env.test &&
          cat ./backend/.env.test
    - run: cd backend && npm run test
      env:
        CI: true
    - run: cd frontend && npm install
    - run: cd frontend/src/app && npm run codecov
    - name: Codecov report
      uses: actions/checkout@master
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: ./backend/coverage/lcov.info,./frontend/coverage/lcov.info # optional
        flags: MEAN-Stack-Demo-TESTS # optional
        name: codecov-test-coverage # optional
        fail_ci_if_error: true # optional (default = false)