name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:   
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd backend && npm install
    - run: cd backend && npm run build --if-present
    - run: touch ./backend/.env.test && 
          echo MONGO_DB_URL=mongodb://127.0.0.1:27001/jest >> ./backend/.env.test && 
          echo SECRET_TOKEN=testingToken >> ./backend/.env.test && 
          cat ./backend/.env.test
    - run: cd backend && npm test
      env:
        CI: true,
        MONGO_DB_URL: mongodb://127.0.0.1:27001/jest,
        SECRET_TOKEN: testingToken